// Assembles the downloadable robot_package.zip:
//
//   robot.urdf
//   meshes/visual/*  meshes/collision/*
//   preview_pybullet.py
//   robot_model.json
//   validation_report.json
//   README.txt

import JSZip from "jszip";
import type { RobotModel } from "../types/robot";
import { buildUrdf } from "./urdf";
import { buildPreviewScript } from "./pybullet";
import { serializeProject } from "./projectIO";
import { validateModel } from "./validation";
import { resolveMeshPlacements } from "./meshPaths";

export interface PackageResult {
  blob: Blob;
  fileName: string;
}

/**
 * A package entry. Plain strings are UTF-8 text files; `{ base64 }` entries
 * carry binary content (e.g. binary STL) that must be written to the zip as
 * bytes, not re-encoded as text.
 */
export type PackageEntry = string | { base64: string };

const README = `Robot package generated by Web CAD / URDF Editor.

Contents:
  robot.urdf              URDF model (collision = primitives, visual = primitives/meshes)
  meshes/visual/          visual mesh files (STL/OBJ), referenced by relative path
  meshes/collision/       collision mesh files, if any
  preview_pybullet.py     PyBullet GUI preview with joint sliders
  robot_model.json        editor project file (re-loadable)
  validation_report.json  errors & warnings at export time

Quick start:
  pip install pybullet
  python preview_pybullet.py
`;

/** Build the in-memory file map of the package (used by tests and the zipper). */
export function buildPackageFiles(model: RobotModel): Record<string, PackageEntry> {
  const files: Record<string, PackageEntry> = {
    "robot.urdf": buildUrdf(model),
    "preview_pybullet.py": buildPreviewScript(model),
    "robot_model.json": serializeProject(model),
    "validation_report.json": JSON.stringify(validateModel(model), null, 2),
    "README.txt": README,
  };

  const placements = resolveMeshPlacements(model);
  const meshById = new Map(model.meshes.map((m) => [m.id, m]));
  for (const placement of placements.values()) {
    const mesh = meshById.get(placement.meshId);
    if (!mesh) continue;
    // Preserve binary STL bytes verbatim; ASCII meshes stay as text.
    const entry: PackageEntry =
      mesh.encoding === "base64" ? { base64: mesh.data } : mesh.data;
    if (placement.visualPath) files[placement.visualPath] = entry;
    if (placement.collisionPath) files[placement.collisionPath] = entry;
  }
  return files;
}

/** Build the package as a downloadable zip blob. */
export async function buildPackage(model: RobotModel): Promise<PackageResult> {
  const zip = new JSZip();
  const files = buildPackageFiles(model);
  for (const [path, content] of Object.entries(files)) {
    if (typeof content === "string") zip.file(path, content);
    else zip.file(path, content.base64, { base64: true });
  }
  const blob = await zip.generateAsync({ type: "blob" });
  const safeName = model.name.replace(/[^A-Za-z0-9._-]/g, "_") || "robot";
  return { blob, fileName: `${safeName}_package.zip` };
}
