// Assembles the downloadable robot_package.zip:
//
//   robot.urdf
//   meshes/visual/*  meshes/collision/*
//   preview_pybullet.py
//   robot_model.json
//   validation_report.json
//   README.txt

import JSZip from "jszip";
import type { RobotModel } from "../types/robot";
import { buildUrdf } from "./urdf";
import { buildPreviewScript } from "./pybullet";
import { serializeProject } from "./projectIO";
import { validateModel } from "./validation";
import { resolveMeshPlacements } from "./meshPaths";

export interface PackageResult {
  blob: Blob;
  fileName: string;
}

const README = `Robot package generated by Web CAD / URDF Editor.

Contents:
  robot.urdf              URDF model (collision = primitives, visual = primitives/meshes)
  meshes/visual/          visual mesh files (STL/OBJ), referenced by relative path
  meshes/collision/       collision mesh files, if any
  preview_pybullet.py     PyBullet GUI preview with joint sliders
  robot_model.json        editor project file (re-loadable)
  validation_report.json  errors & warnings at export time

Quick start:
  pip install pybullet
  python preview_pybullet.py
`;

/** Build the in-memory file map of the package (used by tests and the zipper). */
export function buildPackageFiles(model: RobotModel): Record<string, string> {
  const files: Record<string, string> = {
    "robot.urdf": buildUrdf(model),
    "preview_pybullet.py": buildPreviewScript(model),
    "robot_model.json": serializeProject(model),
    "validation_report.json": JSON.stringify(validateModel(model), null, 2),
    "README.txt": README,
  };

  const placements = resolveMeshPlacements(model);
  const meshById = new Map(model.meshes.map((m) => [m.id, m]));
  for (const placement of placements.values()) {
    const mesh = meshById.get(placement.meshId);
    if (!mesh) continue;
    if (placement.visualPath) files[placement.visualPath] = mesh.data;
    if (placement.collisionPath) files[placement.collisionPath] = mesh.data;
  }
  return files;
}

/** Build the package as a downloadable zip blob. */
export async function buildPackage(model: RobotModel): Promise<PackageResult> {
  const zip = new JSZip();
  const files = buildPackageFiles(model);
  for (const [path, content] of Object.entries(files)) {
    zip.file(path, content);
  }
  const blob = await zip.generateAsync({ type: "blob" });
  const safeName = model.name.replace(/[^A-Za-z0-9._-]/g, "_") || "robot";
  return { blob, fileName: `${safeName}_package.zip` };
}

/** Trigger a browser download of a blob. */
export function downloadBlob(blob: Blob, fileName: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/** Trigger a browser download of a text file. */
export function downloadText(text: string, fileName: string, mime = "application/json"): void {
  downloadBlob(new Blob([text], { type: mime }), fileName);
}
